### ISSUE TITLE
Reference to nonexistent enable_s3_endpoint variable?

### ISSUE THREAD

**Issue by jsclarridge** [trussworks/terraform-layout-example#51]
The VPC example references an `enable_s3_endpoint` variable that doesn't exist in the VPC module it's using:
https://github.com/trussworks/terraform-layout-example/blob/5374508a384d9b52557bfe927d075e8577cc0228/modules/aws-example-vpc/main.tf#L74

**Comment by rpdelaney** [comment]
:lock: [InfraSec reserve trello card](https://trello.com/c/Mg7rIiIr/251-investigate-enables3endpoint-variable-in-terraform-layout-example)
