### ISSUE TITLE
License

### ISSUE THREAD

**Issue by bhang** [trussworks/terraform-layout-example#7]
Greetings.

Thank you for making this repository as well as the engineering playbook publicly accessible - I've found it very instructive. After going through the content, I'd like to borrow/emulate the same patterns that have been described in the example and playbook. I understand that the trussworks terraform modules themselves have licenses but these repositories do not. Would you consider adding a license to this repo as well as the [Engineering playbook repo](https://github.com/trussworks/Engineering-Playbook) so that others may use/reference it?

**Comment by dynamike** [comment]
yes, this wasn't intentional. We'll add one shortly. Thanks for the issue!
